[package]
name = "sparse_suffix_tree"
version = "0.1.0"
authors = ["rsy <hoge@huga.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
